language: golang

services:
  - docker

script:
- docker build . -t packer-e2e
- docker image inspect packer-e2e
- docker run -e HYPERONE_PROJECT="any" -e HYPERONE_TOKEN="$H1_TOKEN" -e HYPERONE_ACCESS_TOKEN_SECRET="$H1_TOKEN" packer-e2e bats test/builder_hyperone.bats

